name: CI
on: [push]
env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/provider_pact_test
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  DISABLE_SPRING: 1
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11-alpine
        ports: ['5432:5432']
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10ms
          --health-timeout 500ms
          --health-retries 15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: provider_pact_test
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
      - name: Fetch main for git diff
        run: git fetch --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
      - name: Setup database
        run:  bundle exec rails db:schema:load
      - name: Build and run tests
        run: bundle exec rspec

